# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo
    environment:
      - SOURCE_BRANCH: master


    steps:
      - add_ssh_keys:
          fingerprints:
            - "09:d6:77:5b:8d:9b:0b:58:fb:34:ce:67:25:16:71:33"
      - run: git config --global user.email "hudak.jonathan@gmail.com"
      - run: git config --global user.name "jonathanhudak"
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      # - run: yarn test
      - run: npm run build
      - run: git remote add live git@github.com:jonathanhudak/jonathanhudak.github.io.git
      - run: npm run deploy
      





      